daemons:
  App\Command\Liveticker\CircularLivetickerCommand:
    sleep: 100
    tags:
      - { name: 'console.command', command: 'daemon:liveticker:circular' }

  App\Command\Liveticker\DailyLivetickerCommand:
    sleep: 20
    tags:
      - { name: 'console.command', command: 'daemon:liveticker:daily' }