services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  App\Command\Liveticker\CircularLivetickerCommand:
    tags:
      - { name: 'console.command', command: 'daemon:liveticker:circular' }

  App\Command\Liveticker\DailyLivetickerCommand:
    tags:
      - { name: 'console.command', command: 'daemon:liveticker:daily' }